# packages in environment at D:\Important\Anaconda\envs\advenv:
#
# Name                    Version                   Build  Channel
absl-py                   0.9.0            py37hc8dfbb8_1    conda-forge
advertorch                0.2.3                    pypi_0    pypi
blas                      1.0                         mkl  
ca-certificates           2020.12.5            h5b45459_0    conda-forge
certifi                   2020.12.5        py37h03978a9_1    conda-forge
cloudpickle               1.4.1                      py_0    conda-forge
cudatoolkit               10.2.89              h74a9793_1  
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.10.1           py37hfa6e2cd_0    conda-forge
dask-core                 2.16.0                     py_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
freetype                  2.10.2               hd328e21_0    conda-forge
future                    0.18.2           py37hc8dfbb8_1    conda-forge
geos                      3.8.1                he025d50_0    conda-forge
grpcio                    1.23.0           py37h3f65fb1_1    conda-forge
icc_rt                    2019.0.0             h0cc432a_1  
icu                       64.2                 he025d50_1    conda-forge
imagecodecs-lite          2019.12.3        py37h8055547_0    conda-forge
imageio                   2.8.0                      py_0    conda-forge
importlib-metadata        1.6.0            py37hc8dfbb8_0    conda-forge
intel-openmp              2019.4                      245  
joblib                    0.15.1                     py_0    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
kiwisolver                1.2.0            py37heaa310e_0    conda-forge
libblas                   3.8.0                    14_mkl    conda-forge
libcblas                  3.8.0                    14_mkl    conda-forge
libclang                  9.0.1           default_hf44288c_0    conda-forge
liblapack                 3.8.0                    14_mkl    conda-forge
liblapacke                3.8.0                    14_mkl    conda-forge
libopencv                 4.2.0                    py37_6    conda-forge
libpng                    1.6.37               hfe6a214_1    conda-forge
libprotobuf               3.11.4               h1a1b453_0    conda-forge
libtiff                   4.1.0                h885aae3_6    conda-forge
libwebp                   1.0.2                hfa6e2cd_5    conda-forge
lz4-c                     1.9.2                h62dcd97_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6  
m2w64-gcc-libs            5.3.0                         7  
m2w64-gcc-libs-core       5.3.0                         7  
m2w64-gmp                 6.1.0                         2  
m2w64-libwinpthread-git   5.0.0.4634.697f757               2  
markdown                  3.2.2                      py_0    conda-forge
matplotlib-base           3.2.1            py37h911224e_0    conda-forge
mkl                       2019.4                      245  
mkl-service               2.3.0            py37hfa6e2cd_0    conda-forge
msys2-conda-epoch         20160418                      1  
networkx                  2.4                        py_1    conda-forge
ninja                     1.10.0               h1ad3211_0    conda-forge
numpy                     1.18.4           py37hae9e721_0    conda-forge
olefile                   0.46                       py_0    conda-forge
opencv                    4.2.0                    py37_6    conda-forge
openssl                   1.1.1j               h8ffe710_0    conda-forge
pillow                    7.1.2            py37hc826c6e_0    conda-forge
pip                       20.1.1             pyh9f0ad1d_0    conda-forge
protobuf                  3.11.4           py37h5fe3f0a_1    conda-forge
py-opencv                 4.2.0            py37h43977f1_6    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyreadline                2.1                   py37_1001    conda-forge
python                    3.7.6           h60c2a47_5_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-wget               3.2                        py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.5.0           py3.7_cuda102_cudnn7_0    pytorch
pywavelets                1.1.1            py37h44b1f71_1    conda-forge
qt                        5.12.5               h7ef1ec2_0    conda-forge
scikit-image              0.17.2           py37h3bbf574_0    conda-forge
scikit-learn              0.22.2.post1     py37h7208079_0    conda-forge
scipy                     1.3.2            py37h29ff71c_0  
setuptools                46.4.0           py37hc8dfbb8_0    conda-forge
shapely                   1.7.0            py37he1cf020_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.30.1               hfa6e2cd_0    conda-forge
tensorboard               2.0.0              pyhb38c66f_1  
tifffile                  2020.5.11                  py_0    conda-forge
tk                        8.6.10               hfa6e2cd_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
torchsummary              1.5.1                    pypi_0    pypi
torchvision               0.6.0                py37_cu102    pytorch
tornado                   6.0.4            py37hfa6e2cd_0    conda-forge
tqdm                      4.46.0             pyh9f0ad1d_0    conda-forge
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
werkzeug                  1.0.1              pyh9f0ad1d_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
wincertstore              0.2                   py37_1003    conda-forge
xz                        5.2.5                h2fa13f4_0    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h2fa13f4_1006    conda-forge
zstd                      1.4.4                h9f78265_3    conda-forge
